---find out highest earner first_name in meployees table

SELECT MAX(SALARY) FROM EMPLOYEES ;

SELECT FIRST_NAME FROM EMPLOYEES
WHERE SALARY = 24000 ;

SELECT FIRST_NAME FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES ) ; -- QUERY INSIDE QUERY

--using abovbe query find out first_name, last_name of minimum earner

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE SALARY =(SELECT MIN(SALARY)FROM EMPLOYEES);
--using abovbe query find out first_name, last_name of all employees above average

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY)FROM EMPLOYEES);

--SECOND MAX SALARY FROM EMPLOYEES

SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY != (SELECT MAX(SALARY)FROM EMPLOYEES);
--WHERE SALARY != 24000;

--FIND OUT THE NAME OF ABOVE PERSON

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = 17000;

--DIFFERENT APPROACH
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY)FROM EMPLOYEES
             WHERE SALARY != (SELECT MAX(SALARY)FROM EMPLOYEES));

--HOW TO RETURN MAX AND MIN SALARY IN ONNE COLUMN
--THE COLUMN NAME SHOULD BE RESULT, IT SHOULD HAVE 2 ROWS

SELECT MAX(SALARY) AS RESULT FROM EMPLOYEES
UNION
SELECT MIN(SALARY) AS RESULT FROM EMPLOYEES ;

--FIND OUT THE NAME OF PEOPLE WHO MAKES 2100 AND 24000

SELECT FIRST_NAME , SALARY
FROM EMPLOYEES
WHERE SALARY IN(2100, 24000) ;

--NOE REMOVE THOSE MAX AND MIN SALARY YOU HARD-CODED IN ABOVE QUERY

SELECT FIRST_NAME , SALARY
FROM EMPLOYEES
WHERE SALARY IN(SELECT MAX(SALARY) AS RESULT FROM EMPLOYEES
             UNION
             SELECT MIN(SALARY) AS RESULT FROM EMPLOYEES) ;








